// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	MenuItems          string
	OrderItems         string
	Orders             string
	PaypalTransactions string
	SchemaMigrations   string
	Users              string
}{
	MenuItems:          "menu_items",
	OrderItems:         "order_items",
	Orders:             "orders",
	PaypalTransactions: "paypal_transactions",
	SchemaMigrations:   "schema_migrations",
	Users:              "users",
}
